### ISSUE TITLE
Does not work on MI TV 4X Running Android TV OS 9.0.

### ISSUE THREAD

**Issue by jagdishadusumalli** [visnkmr/wfm#159]
On MI TV 4X Running Android TV OS 9.0...
The app does not detect/ mount the External USB Drive also with the Internal Disk selected the File Explorer does not show any Files and Folders...
Tried X-plore File Manager which did the both..So its not the TV or ATVOS issue..

I am ready to help and debug the issue.

**Comment by visnkmr** [comment]
Hey, 

Glad you are willing to help us debug the issue, but if you are using the google play store version of the app it is a severely restricted iteration of the app that does not even need storage permission to work. It is a minimal version that uses Storage access Framework, therefore it may not detect/support sending and receiving files from external storage even if you mount the External USB Drive as an Internal Disk on your version of android, as it is mostly geared towards android 11 and above. The amazon appstore version should support the expected features on your Android 9.0 device. You can also find the apk of the amazon appstore version on github as well.

If you do end up trying the apk, do tell me if it worked as you expected and what your take is on the new [OSS Web GUI](https://github.com/visnkmr/wfmossfrontend)?
Thanks.
