### ISSUE TITLE
Wrong folder for uploaded/sent files

### ISSUE THREAD

**Issue by irodrigomiele** [visnkmr/wfm#2]
Wrong folder for uploaded/sent files 

Thank you for the Wireless File Manager app. 
But when I choose a folder to upload/send a file, from the iPhone 11 to Mibox S, the uploaded file always go to a default folder, under Android/Installed app folder/Files instead the folder I chose. Can you help?

**Comment by visnkmr** [comment]
Hey, Glad to know that you found our app useful. Currently, in order to ensure compatibility across android versions we had chosen based on user feedback to save the files to the default folder.
