### ISSUE TITLE
app wont open

### ISSUE THREAD

**Issue by jackm96** [visnkmr/wfm#218]
installed the app from amazon fire store today, getting a message saying it needs to be updated however no updates in the app store and wont go past the message to allow you to use the app

**Comment by daniel3xxx** [comment]
@visnkmr can you make the splash screen skippable? Otherwise is impossible to utilize the application...

**Comment by visnkmr** [comment]
Hey,
If you are reffering to wireless file manager update notification, updating the app should get rid of it?

Thanks.

**Comment by daniel3xxx** [comment]
The update is not yet available on my firestick (Appstore). Because of that i can't use the app.

**Comment by visnkmr** [comment]
> The update is not yet available on my firestick (Appstore). Because of that i can't use the app.

please refer https://github.com/visnkmr/wfm/issues/219#issuecomment-1856452916
