### ISSUE TITLE
Wirless file manager on firestick closes when i connect it to my pc

### ISSUE THREAD

**Issue by Omario88** [visnkmr/wfm#230]
i have tried to uninstall it and reinstall it but it doesn't work and i can't send files like this because i can't manage to make a connection without the app freezing and closing

**Comment by visnkmr** [comment]
hey,
If you are able to click on start wireless file manager button could you try to open the webui using http://<ipaddress>:<port>/old and see if it works.

Assumptions:
If you are able to click on start wireless file manager button
You are using the latest version of the app available either downlaoded from amazon appstore or from our appstore.

Thanks.

**Comment by Omario88** [comment]
i have already tried opening the old version,and yes i'm the the newest option,i've tried to install wfm from both the amazon appstore and the github

**Comment by visnkmr** [comment]
If I'm guessing correct you are able to click on "start wireless file manager" option and after connection, when you try to select a file to upload and click on upload the app crashes, right?

**Comment by Omario88** [comment]
it was like that until yesterday,from yesterday it crashes after 3/4 seconds the connection and in those seconds the app is freezed

**Comment by visnkmr** [comment]
Hey, could you tell me which version of the app you are using ?

**Comment by Omario88** [comment]
Sorry for the late reply,i'm using version 2.3A8i
