### ISSUE TITLE
Wireless file manager

### ISSUE THREAD

**Issue by GitStudying** [visnkmr/wfm#231]
This app really improves performance and management of Chromecast with Google TV. When I click on wireless file manager, it says not installed and then I go to open app in appstore. I then get item not found. I am not sure but it is either not available at all or not available in my region. Could you maybe refer to the apk if the item is not available on the play store. The same story goes for the Internet speed meter for TV in quick shortcuts

Another unrelated question. Is the app open source, you do have this github repo but I don't see any source code. Do you have another place for that or is it just closed-source.

**Comment by visnkmr** [comment]
Hey,
Glad you found the app useful. Regarding the query,

> This app really improves performance and management of Chromecast with Google TV. When I click on wireless file manager, it says not installed and then I go to open app in appstore. I then get item not found. I am not sure but it is either not available at all or not available in my region. Could you maybe refer to the apk if the item is not available on the play store. The same story goes for the Internet speed meter for TV in quick shortcuts

The app has been removed by us from Google Play, regarding the apk and where it can be found please refer https://github.com/visnkmr/wfm/issues/222#issuecomment-1848265970

> 
> Another unrelated question. Is the app open source, you do have this github repo but I don't see any source code. Do you have another place for that or is it just closed-source.
The app source code is currently not available publicly. We will update on https://visnkmr.github.io/ if ever the source code is published.
