### ISSUE TITLE
Wireless manager app not opening giving error message

### ISSUE THREAD

**Issue by dishwara** [visnkmr/wfm#235]
Hi,
I was using wireless file manager app on my xiaomi tv.
Suddenly app not working, saying to update.
But update downloaded from your site https://visnkmr.github.io/appstore/details/Wireless%20File%20Manager not installing.
My version is SAF0.1G6I
Please update app.
Thank you.

**Comment by davotoula** [comment]
Same

**Comment by davotoula** [comment]
Problem still persists

**Comment by visnkmr** [comment]
Please uninstall the existing version and then try to install the apk from the link. It should fix the issue.

**Comment by visnkmr** [comment]
This is because the version number is different between the Play store version and Github/My appstore version

**Comment by davotoula** [comment]
I have unistalled from firestick and reinstalled but still same error.

I cannot sideload without being able to use the wireless manager!

**Comment by visnkmr** [comment]
Please try using version 2.3a9i which was uploaded just 2 days ago. Is it still showing the update error?

**Comment by davotoula** [comment]
Has the latest version been pushed to amazon app store correctly?

**Comment by visnkmr** [comment]
yes. This has been a persistent issue for sometime now,even though a newer version of an app is available some users are unable to download it, some have been facing this very issue frequently as evident from frequent github issue reports we are getting regarding the same. I'm guessing since they are planning on moving away from Fire OS and Amazon Appstore, this may be the result of that.

**Comment by visnkmr** [comment]
> version is SAF0.1G6I

The original author of this issue mentioned he was using google play based device so i assumed you were using the same.

**Comment by davotoula** [comment]
Apologies for hijacking the thread. This issue is for amazon app store.

! [17057718576230.jpg](https://github.com/visnkmr/wfm/assets/1747287/0889d742-46b1-409a-9788-7b51a1626382)

![17057718576951.jpg](https://github.com/visnkmr/wfm/assets/1747287/c62ee65b-92ff-46a0-8278-7438f8b1236b)

**Comment by visnkmr** [comment]
in the second screenshot the what's new section lists 2.3a9i , but the version being installed is version 2.3a6i evident from first screenshot. This has been a persistent issue for most users. That's why if you prefer you can use the apk from our appstore.
