### ISSUE TITLE
Open on TV not working

### ISSUE THREAD

**Issue by Bibididi** [visnkmr/wfm#245]
Hi,

Since the last update I cannot play the videos uploaded to the Fire TV wether it is directly on the TV from the WFM app or from the web server. 

There is no error message and the files are downloaded to the Android/data/io.github.visnkmr.wirelessexplorer/files folder instead of the Download folder as they used to.

I really liked this functionnality since I could script the video playing by copying the sent request but it doesn't work anymore.

Regards.

**Comment by visnkmr** [comment]
Hey, I will check up regarding this and get back to you in 24 hours.

@set-reminder remind me tommorow about this.

**Comment by visnkmr** [comment]
@set-reminder remind me in 1 day about checking this issue.

**Comment by visnkmr** [comment]
@Bibididi Could you try using the https://<ip-address>:port/old url and access and play the video it should work as expected.
 Debugging the current issue may take some time since its related to new webUI and firestick and the microinteractions, the new webui seems to work just fine on other android devices but seems there is an issue with using it on fire tvs.

**Comment by visnkmr** [comment]
The file should be located @ /android/data/io.github.visnkmr.wirelessfilemanager/files/

I will try to debug this also along with the other issue

**Comment by Bibididi** [comment]
I tested with the old version and it still doesn't work, I can upload files but cannot play them wether through the old UI or the WFM App.

**Comment by visnkmr** [comment]
Hey,
Some more queries for troubleshooting,
Upon hitting play does the app crash and take you back to the homescreen? If yes then it will need some more troubleshooting, if not then Which app was the video being played by previously? Is it VLC or have you installed any other such media player. Cause Wireless File Mnager does not play the video by itself it launches the video in the installed media player on your device. If you have none installed it may be reason why the video isnt being played?

**Comment by Bibididi** [comment]
Hi,
My bad on that one, I forgot to download mxplayer on this new TV.
With it installed its working as intended.

Regards,

**Comment by visnkmr** [comment]
> Hi, My bad on that one, I forgot to download mxplayer on this new TV. With it installed its working as intended.
> 
> Regards,

Hey,
the closing of wireless file manager was an issue with applist component and i have temporarily removed icons of apps that were shown in the new WebUI. The update that does all this is now available on github, our appstore and will be available amazon appstore in 1-3 days. Thanks for reporting and troubleshooting it with us.
