### ISSUE TITLE
Obsolete app?

### ISSUE THREAD

**Issue by shlomster** [visnkmr/wfm#269]
Downloaded wireless file manager onto Fire TV Stick 4K Max. Fire OS 7.6.6.8

Opened the app got a message stating:
The version of app you have installed is2.3A6i
Today's date as per your device is [correct date]
You are seeing this message because
-your device time is incorrect.

If your device time is correct.
-Then you are using an obsolete(very old) version of the app; check for app updates on github....

Is this app truly outdated?

Interestingly, I can't seem to use the remote to access the OK or update app buttons at the bottom. I can only modify the change text size slider at the top.

**Comment by visnkmr** [comment]
yes. This has been a persistent issue for sometime now,even though a newer version of an app is available some users are unable to download it, some have been facing this very issue frequently as evident from frequent github issue reports we are getting regarding the same.

You can find more regarding the issue @ https://github.com/visnkmr/wfm/issues/235

In the meantime you can find and download app updates @ https://visnkmr.github.io/appstore
