### ISSUE TITLE
Shortcut For Uploaded Files

### ISSUE THREAD

**Issue by phnord** [visnkmr/wfm#272]
Files currently get uploaded to /Android/data/io.github.visnkmr.wirelessexplorer/files/

That's a pain to navigate to afterwards from the Files screen

Suggestion: a button on the main nav-bar, or a shortcut in the files list, to bring you straight to that directory

**Comment by visnkmr** [comment]
Feel free to correct me if I'm wrong, I guessing  you are referring to a fire stick and want the files app of ours to have a shortcut to open the folder that wfm uploads to. If that is it I 'l look into what can be done regarding this.
