### ISSUE TITLE
Suggestion: URLs for various destinations in the web-app

### ISSUE THREAD

**Issue by phnord** [visnkmr/wfm#273]
As you use the app, the URL stays the same.  This is unideal for actually using and navigating the app

It would be far more functional if you were to have, for instance, "/upload" open the uploads tab – or something like "?directory=/Music/" which updates as you browse, and which could be used to navigate to a specific directory

This would be great for both using forward / backward buttons in-browser, and for being able to bookmark / link to specific locations or features

**Comment by visnkmr** [comment]
> As you use the app, the URL stays the same. This is unideal for actually using and navigating the app
> 
> It would be far more functional if you were to have, for instance, "/upload" open the uploads tab – or something like "?directory=/Music/" which updates as you browse, and which could be used to navigate to a specific directory
> 
> This would be great for both using forward / backward buttons in-browser, and for being able to bookmark / link to specific locations or features

The old version does have it. You can find it @ http://ipaddress:port/old
in the new version we will implement it in the future or before if someone else does it via a PR or something the code is open source and can be browsed @ https://github.com/visnkmr/wfmossfrontend
