### ISSUE TITLE
Cuurent Version installed

### ISSUE THREAD

**Issue by NotThePassword** [visnkmr/wfm#288]
WFM 2.3A6i

Date is correct, but says to remind someone to update the app here?

**Comment by Amishtek** [comment]
same issue on my androidtv popup now states  I have SAF0.1G6I and the app is no longer in the androidtv app store to upgrade if there is one.

**Comment by visnkmr** [comment]
The app is no longer available on Google play. It is available on Amazon appstore. You can find it on our [appstore](https://visnkmr.github.io/appstore) as well.

**Comment by dgoodyear11** [comment]
I did this just now and loaded the app from the link, but the result is the same - I still get the overlay about checking the date.  Please advise.

**Comment by visnkmr** [comment]
That's strange i just installed it using the apk from https://visnkmr.github.io/appstore and it worked just fine. Will wait for more user feedback since its not reproducible by me. If you're still using one installed from google play then it wont work since its no longer available on Google Play.

**Comment by tomatoteach** [comment]
![20240531_190451](https://github.com/visnkmr/wfm/assets/171374932/25775cc8-754a-4397-8a3d-df1396e48ad7)
I started to have the same error saying "your device time is incorrect".  I tried to uninstall previous version and download it both from appstore and https://visnkmr.github.io/appstore again. But the error still exists. Version installed is is2.3A9i. Could you please help advise? Thanks.

**Comment by visnkmr** [comment]
the latest version is 2.3a10i and it has been available on amazon appstore since a week or so, it is also available on our appstore also.

**Comment by tomatoteach** [comment]
Thanks so much! Problem solved after installed new version. 👍 Will you plan to update the version in Amazon Appstore too? It is 6i and we can install this apps in Fire stick via Amazon Appstore only.
