### ISSUE TITLE
ip webpage wont connect

### ISSUE THREAD

**Issue by tempraryacc** [visnkmr/wfm#351]
I imagine this should be an easy fix since everything else is working well. I have the latest version of this app on my fire tv, but whenever I get to the part where I start it up and I'm given the IP to punch into my browser. I get the error window saying the connection took too long to respond. 

both tv and my computer are connected to the same wifi network. and I tried opening the IP on my phone too. no luck. 

what could the issue be?

**Comment by visnkmr** [comment]
Could you check if old layout works, its accessible @ http://_ipaddress:port_/old

**Comment by tempraryacc** [comment]
sorry for the late reply, was out of state 
I tried the old layout. still nothing
