### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ozdek** [visnkmr/wfm#4]
I am getting this error on Firestick 4k Max

It seems you are using an obsolete (very old) version of the app.
You are seeing this messsage because
-your device time is incorrect
If your device time is correct.
- Then check for app updates in our Telegram channel.

The app is installed through appstore and time is correct.

**Comment by visnkmr** [comment]
Hey,
Thanks for alerting us to this issue. An update for the app will be available soon. We will publish on [our telegram channel](https://t.me/vishnunkmr) once its live.

**Comment by visnkmr** [comment]
Hey, 
The update to fix the issue is available since May 5th. I'm closing the issue for now.
