### ISSUE TITLE
keyboard stay collapsed

### ISSUE THREAD

**Issue by JJHRelateIT** [visnkmr/wfm#43]
HI great app 

but I would love the keyboard to stay collapsed if the user collapses the keyboard. the if the user needs the keyboard they can just press the button to allow the keyboard to expand again. 

currently the keyboard will expand every time the user selects a new field, some user write the previous versions supported this feature but the current does not 

keep up the good work

**Comment by visnkmr** [comment]
the current version also supports totally hiding the keyboard. But if you want it to be displayed again you will have to go into the app and reset the visibility for the keyboard to be shown again.

Vishnu N K
Telegram (https://visnkmr.t.me)
Github (https://github.com/visnkmr) || Codeberg (https://codeberg.org/visnk) || Linkedin (https://www.linkedin.com/in/vishnunk-59124/)
Homepage (https://visnk.pages.dev)
