### ISSUE TITLE
Wfm crashing 

### ISSUE THREAD

**Issue by FirestickWindsor** [visnkmr/wfm#5]
Hello thanks for all you do!! I love your apps and want to say it helps alot of people save time!

On basic Firestick, wfm opens and then crashes after a few seconds. Thanks!!

keep on with the great apps. The world hopefully appreciates what you (and your team)!  Blessings

**Comment by visnkmr** [comment]
Hey, Glad you found our app useful. Regarding the issue, Could you please tell us which version of the app you are facing the issue on?

**Comment by FirestickWindsor** [comment]
Thanks for getting back and resolving the issue!  I use this weekly and it is a time saver for me. I appreciate all you do in helping others with your apps as many probably just enjoy them without letting you know. 

Have a blessed week!
