### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by ozdek** [visnkmr/wfm#6]
I am getting this error on Firestick 4k Max

It seems you are using an obsolete (very old) version of the app.
You are seeing this messsage because
-your device time is incorrect
If your device time is correct.

Then check for app updates in our Telegram channel.
The app is installed through appstore and time is correct.
The version reported is 2.25A3i and time is 29/10/2022.

**Comment by mariosbbs** [comment]
maybe it's dead :-(

**Comment by visnkmr** [comment]
Hey, 
Thanks for reporting this issue. An update has been pushed to amazon appstore today, it may take 2 or more days for the update to become available. We will update on the [telegram channel](https://vishnunkmr.t.me) once the update is live.
