### ISSUE TITLE
Obsolete app isue

### ISSUE THREAD

**Issue by quy0193** [visnkmr/wfm#7]
Hi,

I'm using Google Chromecast 4K (2022) and got the error message that the app is obsolete and need to check for updates in Telegram channel or Appstore but not sure how to do that. Appreciate if you could help with the issue.

**Comment by visnkmr** [comment]
Hey,
Thanks for reporting this issue. An update will be pushed today to google play, it may take upto 24 hours for the update to become available. We will update on the [telegram channel](https://vishnunkmr.t.me/) and here once the update is live.

**Comment by visnkmr** [comment]
Update is now available on Google play.
